# Generated by Django 4.2.6 on 2023-12-12 13:48

from django.db import migrations


def add_data(apps, schema_editor):
    # Используем модели из apps, а не импортируем напрямую
    Landing = apps.get_model('core', 'Landing')
    Page = apps.get_model('core', 'Page')
    
    # Создаем лендинг
    landing = Landing.objects.create(
        name='AllSmiles Redesign',
        domain='allsmiles-impl-redesign.blank.sinergium.ru',
        is_active=True
    )

    # Создаем главную страницу
    Page.objects.create(
        landing=landing,
        title='Главная',
        slug='home',
        content='Главная страница AllSmiles Redesign',
        meta_description='Главная страница AllSmiles Redesign',
        is_active=True
    )

    # Создаем страницу "Спасибо"
    Page.objects.create(
        landing=landing,
        title='Спасибо',
        slug='success',
        content='Спасибо за обращение!',
        meta_description='Спасибо за обращение!',
        is_active=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial')
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
